version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3310:3306"
    networks:
      - dockercompose
    
  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    networks:
      - dockercompose
    volumes:
      - /home/alan/Área de Trabalho/Curso/5_compose/6_bind_mount/flask:/app

networks:
  dockercompose: